### ISSUE TITLE
connection failed at run

### ISSUE THREAD

**Issue by rohitghosal** [EntySec/ghost#209]
# showing connection failed !!
I have prperly installed ghost v6 and i set RHOST to IP Address of the remote host and RPORT 5555 and after its happening.....

[i]Connecting  to RHOST IP:5555
[-]failed to connect RHOST IP:5555!!

**Comment by game-lover** [comment]
@rohitghosal

Read [this issue](#112).

**And next time use default ISSUE TEMPLATE!**

**Comment by rohitghosal** [comment]
Is this problem for shadin.io only!!

**Comment by rohitghosal** [comment]
Can you show me how the default template issue looks like?

**Comment by game-lover** [comment]
---
name: Bug report
about: Create a report to help us improve
title: ''
labels: ''
assignees: ''

---

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]
 - Browser [e.g. chrome, safari]
 - Version [e.g. 22]

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6]
 - OS: [e.g. iOS8.1]
 - Browser [e.g. stock browser, safari]
 - Version [e.g. 22]

**Additional context**
Add any other context about the problem here.

**Comment by rohitghosal** [comment]
Thanks for following helping

**Comment by rohitghosal** [comment]
And one more thing ...my issue is for shadon.io ADB offline issue??
